# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-site:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check env      
      run: pwd
      
    - name: Checkout branch
      uses: actions/checkout@v3
      
    - name: Check status
      run: git status
    
    - name: Download docfx
      run: curl -LO https://github.com/dotnet/docfx/releases/download/v2.59.2/docfx.zip
      
    - name: View content
      run: dir      
